### ISSUE TITLE
haddock-tools/restrain_bodies.py - seed is constant

### ISSUE THREAD

**Issue by mieczyslaw** [haddocking/haddock-tools#18]
@amjjbonvin , @JoaoRodrigues Is that expected that the seed is constant in production version? It makes sense for debugging/testing, but I suppose if the tool intends to pick "random atoms", it is not doing so between runs.

```
# Set random seed to have reproducibility
random.seed(917)
```

**Comment by JoaoRodrigues** [comment]
Hi @mieczyslaw, yup, it should be constant otherwise you will have a hard time reproducing runs.

**Comment by mieczyslaw** [comment]
> Hi @mieczyslaw, yup, it should be constant otherwise you will have a hard time reproducing runs.

I believe that if you'd like to test various antigens with the same antibody, it makes sense to keep the restraints constant, so you are not affecting the antibody dynamics so much. 

But in general, apart from debugging, why do you want to reproduce the runs? Isn't it better that by running a few times, the results can be more stochastic and you can check whether they can be clustered together? 

Why 917 as a seed?

**Comment by JoaoRodrigues** [comment]
So, 917 is historical, it's @amjjbonvin 's fav number :) 

This script is mostly useful when you have gaps in your molecule. The semiflexible refinement will throw an error if you cannot connect all atoms in a molecule through bonds or restraints. It keeps the structure intact, otherwise it could drift apart erroneously.

Stochasticity comes from each molecule at it0. We want users to submit a run today, and submit it again tomorrow and have the same results.

**Comment by mieczyslaw** [comment]
Thanks @JoaoRodrigues !

So for identical run input parameters (restraints, active/passive residues) there is no sense to run HADDOCK twice as the returned results will be the same (or very similar)?

**Comment by JoaoRodrigues** [comment]
Just increase the number of molecules at it0 or explicitly change the random seed :) it's a parameter in the guru interface.

**Comment by mieczyslaw** [comment]
Thank you!

**Comment by JoaoRodrigues** [comment]
Sorry for the terse messages, I was on my phone!

Basically, to sum up. This script kicks in when you have gaps in one of your molecules. It can be because of an actual gap - missing residues - or because you have multiple molecules merged in one 'haddock molecule': e.g. antibodies. Either way, you don't want your molecules to drift away/distort because they are not connected. The focus of HADDOCK is to predict the interface of those molecules with something else. So we keep them sort of rigidly in place. The restraints will still allow for some flexibility, just not for the sub-molecules to move around independently.

**Comment by amjjbonvin** [comment]
The server does the same, defining one set of restraints for all docking models.

**Comment by amjjbonvin** [comment]
917 is a prime number :-)

**Comment by amjjbonvin** [comment]
If run on the same hardware, yes similar results.

Unless you change the random seed in run.cns for each separate run.

**Comment by mieczyslaw** [comment]
Sure! Thanks for explaining!
